name: Matrix Context Example
run-name: Matrix Context Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [10, 12]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Display Matrix Context
      run: |
        echo "Full Matrix: ${{ matrix }}"
        echo "Operating System: ${{ matrix.os }}"
        echo "Node.js Version: ${{ matrix.node }}"
