name: Show secrets
run-name: Show secrets

on:
    push:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    display-secrets-context:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ toJson(secrets) }} | jq"

