name: Upload an artifact
run-name: Upload an artifact

on:
  push:
    branches:
      - "main"

jobs:
  Create-an-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: mkdir -p samplepath
      - run: echo Hello > hello.txt
      - run: ls -ltr|grep hello

