name: Upload an artifact
run-name: Upload an artifact

on:
  push:
    branches:
      - "main"

jobs:
  Create-an-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Get present working dir
        run: pwd
      - name: Create dir samplepath
        run: mkdir -p samplepath
      - name: Create dir artifact
        run: echo ${{ github.run_id }} > samplepath/${{ github.sha }}.txt
      - name: list dir content
        run: ls -ltr samplepath
      - name: Upload a file
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: samplepath/${{ github.sha }}.txt
      - name: again list dir content
        run: ls -ltr


