name: Upload an artifact
run-name: Upload an artifact

on:
  push:
    branches:
      - "main"

jobs:
  Create-an-artifact:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: mkdir -p samplepath
      - run: mkdir -p newpath
      - run: echo Hello > samplepath/hello.txt
      - run: ls -ltr|grep hello
      - name: Upload a file
        uses: actions/upload-artifact@v4
        with:
          name: newpath/my-artifact
          path: sampplepath/hello.txt
      - run: ls -ltr


